In [37]:
import numpy as np
import pandas as pd
import math

In [5]:
name = input("Enter Your Name Please: ")
print(f"welcome {name}!")
age = input("Enter Your Age Please: ")
print(f"{age} is a very good age")
lang = input("Whats Your favorite Programming language: ")
print(f"ohh!! {lang} is a crucial language")

Enter Your Name Please:  sam

welcome sam!

Enter Your Age Please:  23

23 is a very good age

Whats Your favorite Programming language:  python

ohh!! python is a crucial language

In [10]:
gas_price_per_liter = 184.12
liter = 12
oil_price = 540
others =829

total_cost = gas_price_per_liter * liter + oil_price + others
average_price = total_cost / 3
print(f"total_cost is {total_cost} with an average price of {average_price}")

total_cost is 3578.44 with an average price of 1192.8133333333333

In [15]:
num1 =  float(input("Enter Your first number Please: "))
num2 = float(input("Enter Your Second number Please: "))

Sum = num1 + num2
difference = num1 - num2
product =num1 * num2
print(f"sum of {num1} & {num2} is {Sum}. difference of {num1} & {num2} is {difference}. product of {num1} & {num2} is {product}")

Enter Your first number Please:  30
Enter Your Second number Please:  60

sum of 30.0 & 60.0 is 90.0. difference of 30.0 & 60.0 is -30.0. product of 30.0 & 60.0 is 1800.0

In [20]:
score = int(input("Enter your score"))
if score >= 50:
    print("congratulations!! youve passed")
else:
    print(" failed Sorry, next time.")

Enter your score 50

congratulations!! youve passed

In [25]:
grade = int(input("Enter your grade"))
if grade < 60:
    print("F")
elif 61 > grade < 70:
    print("C")
elif 71 > grade < 79:
    print("B")
else:
    print("A")

Enter your grade 34

F

In [29]:
for x in range(1,20):
    if x % 2 == 0:
        print(x)
    else:
        pass

2
4
6
8
10
12
14
16
18

In [36]:
Sum = 0 
current_num = 1

while current_num <= 100:
    Sum += current_num
    current_num += 1

print(f"The sum of 1 to 100 is {Sum}")

The sum of 1 to 100 is 5050

In [32]:
width = int(input("Enter your width"))
length = int(input("Enter your length"))

def rectangle_area(length, width):
    area = length * width
    print(f"the area of your rectangle is {area} m^2")
    
rectangle_area(length, width)

Enter your width 40
Enter your length 50

the area of your rectangle is 2000 m^2

In [41]:
check = lambda x: math.pow(x,2) 

results = [check(x) for x in range(1, 10)] 
results

[1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0]

In [44]:
power_list = [math.pow(x,2) for x in range(1,20)]
power_list

[1.0,
 4.0,
 9.0,
 16.0,
 25.0,
 36.0,
 49.0,
 64.0,
 81.0,
 100.0,
 121.0,
 144.0,
 169.0,
 196.0,
 225.0,
 256.0,
 289.0,
 324.0,
 361.0]

### Section B: NumPy

In [53]:
ls = []
for x in range(1, 20):
    ls.append(x)
arr = np.array(ls) 
arr.shape, arr.dtype, arr.size

((19,), dtype('int64'), 19)

In [63]:
a = np.array([10,20,20,40])
b = np.array([5,10,15,20])

Sum = np.add(a, b)
Sub = np.subtract(a,b)
Mul = np.multiply(a,b)
Div = np.divide(a,b)

print(f"Sum: {Sum}, Subtraction: {Sub}, multplication: {Mul}, Division:{Div}")

Sum: [15 30 35 60], Subtraction: [ 5 10  5 20], multplication: [ 50 200 300 800], Division:[2.         2.         1.33333333 2.        ]

In [67]:
score_arr = np.array([80,60,50,90,78,84])
score_arr_mean = score_arr.mean()
score_arr_max_num = score_arr.max()
score_arr_min_num = score_arr.min()
score_arr_std = score_arr.std()
print(score_arr_mean, score_arr_max_num, score_arr_min_num, score_arr_std)

73.66666666666667 90 50 14.019827229875393

### Section C Pandas

In [74]:
df = pd.DataFrame({
    "Name": ["Alex","Nati","Sami","Tedi","Samantha","Miley"],
    "Age": [23,24,25,23,23, 24],
    "Score": [80, 60, 90,89,95, 40]
})
df.head(3)

   Name  Age  Score
0  Alex   23     80
1  Nati   24     60
2  Sami   25     90

In [75]:
df["Name"]
df[df["Score"] > 70]

       Name  Age  Score
0      Alex   23     80
2      Sami   25     90
3      Tedi   23     89
4  Samantha   23     95

In [76]:
df["Status"] = (df["Score"] >= 50).map({True: 'Pass', False: 'Fail'})
df

       Name  Age  Score Status
0      Alex   23     80   Pass
1      Nati   24     60   Pass
2      Sami   25     90   Pass
3      Tedi   23     89   Pass
4  Samantha   23     95   Pass
5     Miley   24     40   Fail

In [81]:
df.describe().loc[['mean', 'std', "min", "max"]]

            Age      Score
mean  23.666667  75.666667
std    0.816497  21.416505
min   23.000000  40.000000
max   25.000000  95.000000

### Section D: Data Cleaning

In [107]:
df2 = pd.DataFrame({
    "Name": ["Alex","Nati","Sami","Tedi","Samantha","Miley"],
    "Age": [23,24,np.nan,23,23, 24,],
    "Score": [np.nan, 60, 90,89,np.nan, 40]
})

In [108]:
df2.isna().sum()
df2.isna().sum().sum()

np.int64(3)

In [109]:
df2['Age'] = df2['Age'].fillna(df2['Age'].median())
df2['Score'] = df2['Score'].fillna(df2['Score'].mean())
df2

       Name   Age  Score
0      Alex  23.0  69.75
1      Nati  24.0  60.00
2      Sami  23.0  90.00
3      Tedi  23.0  89.00
4  Samantha  23.0  69.75
5     Miley  24.0  40.00

In [116]:
df3 = pd.DataFrame({
    "Name": ["Alex","Nati","Sami","Tedi","Samantha","Sami","Miley"],
    "Age": [23,24,24,23,23,24,24],
    "Score": [70, 60, 90,89,90,90,40]
})


df3.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [118]:
df3.drop_duplicates(keep='last')

       Name  Age  Score
0      Alex   23     70
1      Nati   24     60
3      Tedi   23     89
4  Samantha   23     90
5      Sami   24     90
6     Miley   24     40

In [121]:
city = ["addis ababa", "ADDIS ABABA", "Addis Ababa", "adDis abABa"]
standard = [c.title() for c in city]
standard

['Addis Ababa', 'Addis Ababa', 'Addis Ababa', 'Addis Ababa']

In [137]:
import numpy as np

# Initialize array
age = np.array([21, 25, 230, 30, 19, -5, 27])

age = age.astype(float)


age[age == -5] = np.nan

ValueError: cannot convert float NaN to integer

### Section E: Integrated Data Wrangling

In [129]:
df4 = pd.DataFrame({
    "Name": ["Alex","Nati","Sami","Tedi","Sami"],
    "Age": [23,24,23,np.nan,23],
    "enterance": ["2026-01-05", "05/02/2026", "March 10, 2026", "2026.04.15", "March 10, 2026"]
})

df4.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [130]:
df4.drop_duplicates(keep='last')
df4['Age'] = df4['Age'].fillna(df4['Age'].mean())
df4["enterance"] = pd.to_datetime(df4["enterance"], format='mixed')
df4

   Name   Age       enterance
0  Alex  23.0      2026-01-05
1  Nati  24.0      05/02/2026
2  Sami  23.0  March 10, 2026
3  Tedi   NaN      2026.04.15
4  Sami  23.0  March 10, 2026

In [136]:
df5 = pd.DataFrame({
    "sales": [3500,4000,4200,60000,3900,4100,4500,93424]
})
Q1 = df5['sales'].quantile(.25)
Q3 = df5['sales'].quantile(.75)

IQR = Q3 - Q1
lower  = Q1 - 1.5 * IQR
upper  = Q3 + 1.5 * IQR

outliers = df5[
    (df5['sales'] < lower) | (df5['sales'] > upper)
    ]

outliers

   sales
3  60000
7  93424