In [1]:
import pandas as pd

In [46]:
student_id= [101,102,103,102,104,101]
name = ["Abel","Sara","John","Sara","Helen","Abel"]
score = [80,90,75,90,88,80]

In [47]:
df = pd.DataFrame({
    "student_id": student_id,
    "name": name,
    "score": score,
})
df

   student_id   name  score
0         101   Abel     80
1         102   Sara     90
2         103   John     75
3         102   Sara     90
4         104  Helen     88
5         101   Abel     80

In [12]:
df.duplicated().sum()

np.int64(2)

In [37]:
df_clean = df.drop_duplicates()
df_last = df.drop_duplicates(keep="last")

In [13]:
df2 =pd.DataFrame({
    "id": [101,102,103,102,104,101],
    "email": ["a@gmail.com","b@gmail.com","c@gmail.com","a@gmail.com","b@gmail.com","d@gmail.com",]
})
df2

    id        email
0  101  a@gmail.com
1  102  b@gmail.com
2  103  c@gmail.com
3  102  a@gmail.com
4  104  b@gmail.com
5  101  d@gmail.com

In [16]:
df2[df2.duplicated(subset=["email"])]
df2.drop_duplicates(subset=["email"])

    id        email
0  101  a@gmail.com
1  102  b@gmail.com
2  103  c@gmail.com
5  101  d@gmail.com

In [20]:
df3 =pd.DataFrame({
    "city": ["addis ababa", "ADDIS ABABA", "Addis Ababa", "adDis abABa"]
})
df3['city'].str.title()

0    Addis Ababa
1    Addis Ababa
2    Addis Ababa
3    Addis Ababa
Name: city, dtype: object

In [24]:
df4 = pd.DataFrame({
    "name": [" Abel","   Sara","John   ","Sa   ra","Hel en","  Abel"],

})

df4['name'].str.strip()
df4['name'].str.replace(r'\s', '', regex=True)

0     Abel
1     Sara
2     John
3     Sara
4    Helen
5     Abel
Name: name, dtype: object

In [44]:
df5 = pd.DataFrame({
    "date": ["2026-01-05", "05/02/2026", "March 10, 2026", "2026.04.15"]
})
df5["date"] = pd.to_datetime(df5["date"], format='mixed')
df5['date'].dt.month

0    1
1    5
2    3
3    4
Name: date, dtype: int32

In [36]:
df6 = pd.DataFrame({
    "weight_kg": [55,70,85,100]
})
df6["weight_lbs"] = (df6["weight_kg"] * 2.2046).round(2)
df6

   weight_kg  weight_lbs
0         55      121.25
1         70      154.32
2         85      187.39
3        100      220.46

In [39]:
exc_rate = 185
df7 = pd.DataFrame({
    "salary_usd":[500,800,1200,1500]
})
df7['salary_usd'] * exc_rate

0     92500
1    148000
2    222000
3    277500
Name: salary_usd, dtype: int64

In [62]:
df8 = pd.DataFrame({
    "salary": [3500,4000,4200,3900,4100,4500,93424]
})
Q1 = df8['salary'].quantile(.25)
Q3 = df8['salary'].quantile(.75)

IQR = Q3 - Q1
lower  = Q1 - 1.5 * IQR
upper  = Q3 + 1.5 * IQR

outliers = df8[
    (df8['salary'] < lower) | (df8['salary'] > upper)
    ]

outliers

clean_df = df8[
    (df8['salary'] >= lower) & (df8['salary'] <= upper)
    
]
clean_df

   salary
0    3500
1    4000
2    4200
3    3900
4    4100
5    4500